# Header
menu:
  #ä¸»é¡µ: /archives
  #ä¸»é¡µ: /
  å‰ç«¯å¼€å‘: /categories/front
  å·¥ä½œæ—¥å¿—: /categories/work
  ä½åŸæµ…è°ˆ: /categories/life
  å…³äºæˆ‘: /resume

subnav:
  github: "https://github.com/Kiritor"
  weibo: "http://weibo.com/3206206100/profile?topnav=1&wvr=6"
  rss: "/atom.xml"
  zhihu: "http://www.zhihu.com/people/kiritor"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: More
archive_yearly: true #æŒ‰å¹´å­˜æ¡£
fancybox: true
mathjax: false

# Miscellaneous
google_analytics: ''
favicon: /img/favicon.ico

#ä½ çš„å¤´åƒurl
avatar: "http://kiritor.github.io/img/lcore.jpg"

#æ˜¯å¦å¼€å¯åˆ†äº«
socialShare: true

#æ˜¯å¦å¼€å¯äº‘æ ‡ç­¾
tagcloud: true

#æ˜¯å¦å¼€å¯è¯„è®º
valine: true
#æ˜¯å¦å¼€å¯å¤šè¯´æœ€è¿‘è¯„è®º:æ‚¬æµ®äºé¦–é¡µ(ç›®å‰å¼ƒç”¨å¤šè¯´)
#recentComment: false

#æ˜¯å¦å¼€å¯æèµ 
donate: true

#æ˜¯å¦å¼€å¯ç«™å†…æœç´¢
search: true

#æ˜¯å¦å¼€å¯ç›®å½•
toc: true

#æ˜¯å¦å¼€å¯æœ€è¿‘é€šçŸ¥
recent: true
recentContent: ğŸç °ç °åœ¨å·¦è¾¹,ä½ åœ¨ç °ç °é‡Œ...

#æ˜¯å¦å¼€å¯å¾®ç®€å†
resume: false

#æ˜¯å¦å¼€å¯å‹æƒ…é“¾æ¥
#ä¸å¼€å¯â€”â€”
friends: false
#å¼€å¯â€”â€”
#friends:
  #å¥¥å·´é©¬çš„åšå®¢: http://localhost:4000/
  #å¡å¡çš„ç¾ä¸½ä¼ è¯´: http://localhost:4000/
   #æœ¬æ³½é©¬çš„åšå®¢: http://localhost:4000/
  #å‰æ ¼æ–¯çš„åšå®¢: http://localhost:4000/
  #ä¹ å¤§å¤§å¤§ä¸åŒ: http://localhost:4000/
  #æ‰˜è’‚çš„åšå®¢: http://localhost:4000/

#æ˜¯å¦å¼€å¯â€œå…³äºæˆ‘â€ã€‚
#ä¸å¼€å¯â€”â€”
#aboutme: false
#å¼€å¯â€”â€”
# aboutme: ä¹äºåˆ†äº«,å–œæ¬¢ç¯å¢ƒéŸ³ä¹,çˆ±çœ‹åŠ¨æ¼«,å¶å°”å†™å†™æŠ€æœ¯åšå®¢çš„å°ç¨‹ä¸€æš...
